# Generated by Django 4.0.4 on 2022-12-20 06:39

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, help_text='متن مورد نظر', max_length=5000, null=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='اخرین بروز رسانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='تاریخ ایجاد')),
                ('chosen', models.BooleanField(default=False, help_text='انتخاب شده')),
            ],
        ),
    ]
