# Generated by Django 4.0.4 on 2022-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام مهارت', max_length=255)),
                ('desc', models.CharField(blank=True, help_text='توضیحات', max_length=5000, null=True)),
                ('percent', models.FloatField(help_text='میزان مهارت', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ اخرین به روز رسانی')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
